---
name: Programar en objetos es contar historias
locale: es
type: learning
beta: false
teacher_info: ''
language: wollok
id_format: "%05d"
order:
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 10
- 9
- 8
private: false
